version: 2.1

jobs:
  will_fail:
    resource_class: small
    docker:
      - image: cimg/base:stable
    parallelism: 3
    steps:
      - run:
          name: mock test
          command: |
            sleep 3
            if [ "${CIRCLE_NODE_INDEX}" -eq 0 ]; then 
              echo "failing..."
              exit 1
            else
              sleep 60
            fi
      - run:
          # see https://circleci.com/docs/configuration-reference/#ending-a-job-from-within-a-step
          name: halt job on failure
          when: on_fail
          command: |
            echo "stopping this job!"
            circleci-agent step halt

workflows:
  main:
    jobs:
      - will_fail
