version: 2.1

jobs:
  build:
    environment:
      FOO: bar
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: |
          printenv FOO
      - run: |
          if [ "${FOO}" = "bar" ]; then
            echo "halting..."
            circleci-agent step halt
            echo "halted!"
          fi
          
          echo "still running?"
      - run: |
          echo "continued"

  noop:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "noop"
      
workflows:
  main:
    jobs:
      - build
      - noop:
          requires:
            - build
